name: CI
on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build web & Prepare deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: git config user.name "deploy" && git config user.email "deploy@noove.org"
      - name: Deploy
        uses: borales/actions-yarn@v4
        with:
          cmd: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
